server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: 192.168.15.207
      port: 8500
    gateway:
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/users/**
        filters:
          - RewritePath=/users/?(?<path>.*), /$\{path}
      - id: auth-service
        uri: lb://auth-service
        predicates:
        - Path=/auth/**
        filters:
          - RewritePath=/auth/?(?<path>.*), /$\{path}
